{
# 公众号配置
# 公众号appId
"app_id": "wxce35ff0c22e156b3",
# 公众号appSecret
"app_secret": "0f546d6f480ae18b06d39c007c4e69d8",
# 模板消息id
"template_id": "GqFlsVqJo7UCnJrQmXTZQ8j0wHXncPmRtn4-vIrV6XQ",
# 接收公众号消息的微信号，如果有多个，需要在[]里用英文逗号间隔，例如["wx1", "wx2"]
"user": ["om12d59LWf1auM6S1cFuRjWTDHkg"],

# 信息配置
# 所在省份
"province": "四川",
# 所在城市
"city": "绵阳",
# 生日1，修改名字为对应需要显示的名字，如果生日为农历，在最前面加上r即可
"birthday1": {"name": "宝宝", "birthday": "r2001-08-03"},
# 生日2
"birthday2": {"name": "宝贝", "birthday": "r1999-08-18"},
# 在一起的日子，格式同上
"love_date": "2020-10-08"
}
